--- stdlib error setup (errors.Join) ---
*** In our own error handling practices, the complete error message text is dependent on unwrapping (e.g. errs.JoinMessage). However, this clashes with stdlib expectations.
ourlib joined msg...
 ? |-
    No checkout: No project access: No authorization: HTTP 404
    Local cache unavailable: Service unreachable
:   ? |-
        No project access: No authorization: HTTP 404
        Local cache unavailable: Service unreachable
    :   ? |-
            No authorization: HTTP 404
            Local cache unavailable: Service unreachable
        :   - |-
              HTTP 404
              Local cache unavailable: Service unreachable
            - HTTP 404
            - 'Local cache unavailable: Service unreachable': Service unreachable

*** In the stdlib error handling practices, the error message is its own message prepended to the wrapped errors messages. We only need to print the output of err.Error().
stdlib unwrapped...
No checkout: No project access: No authorization: HTTP 404\nLocal cache unavailable: Service unreachable {
    No project access: No authorization: HTTP 404\nLocal cache unavailable: Service unreachable {
        No authorization: HTTP 404\nLocal cache unavailable: Service unreachable {
            HTTP 404\nLocal cache unavailable: Service unreachable {
                HTTP 404 {
                Local cache unavailable: Service unreachable {
                    Service unreachable {

--- stdlib error setup (fmt.Errorf 2x %w) ---
ourlib joined msg...
 'No checkout: No project access: No authorization: [HTTP 404 | Local cache unavailable: Service unreachable]':
    'No project access: No authorization: [HTTP 404 | Local cache unavailable: Service unreachable]':
        - 'No authorization: [HTTP 404 | Local cache unavailable: Service unreachable]'
        - HTTP 404
        - 'Local cache unavailable: Service unreachable': Service unreachable

*** Notice how joining errors using double %w verbs means that the default newline formatting of errs.Join does not show up. Many people dislike the newline as a default.
stdlib unwrapped...
No checkout: No project access: No authorization: [HTTP 404 | Local cache unavailable: Service unreachable] {
    No project access: No authorization: [HTTP 404 | Local cache unavailable: Service unreachable] {
        No authorization: [HTTP 404 | Local cache unavailable: Service unreachable] {
            HTTP 404 {
            Local cache unavailable: Service unreachable {
                Service unreachable {

--- ourlib error setup ---
ourlib joined msg...
 No checkout:
    No project access:
        No authorization:
            - HTTP 404
            - Local cache unavailable: Service unreachable

*** Again, we are dependent on unwrapping (i.e. we cannot simply print err.Error()), and errs.Pack creates an additional dependency on custom multierror handling practices where the multierror message itself should be skipped when outputting a complete error chain message.
stdlib unwrapped...
No checkout {
    No project access {
        No authorization {
            packed multiple errors {
                HTTP 404 {
                Local cache unavailable {
                    Service unreachable {
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4da4c7]

goroutine 1 [running]:
main.printChain(0x6, {0x0, 0x0})
	/home/daved/code/src/github.com/ActiveState/cli/cmd/errwraps/main.go:15 +0x67
main.printChain(0x5, {0x529798, 0xc0000a0300})
	/home/daved/code/src/github.com/ActiveState/cli/cmd/errwraps/main.go:21 +0x1f4
main.printChain(0x4, {0x529798, 0xc0000a0380})
	/home/daved/code/src/github.com/ActiveState/cli/cmd/errwraps/main.go:21 +0x1f4
main.printChain(0x3, {0x529778, 0xc000010270})
	/home/daved/code/src/github.com/ActiveState/cli/cmd/errwraps/main.go:24 +0x22f
main.printChain(0x2, {0x529798, 0xc0000a0400})
	/home/daved/code/src/github.com/ActiveState/cli/cmd/errwraps/main.go:21 +0x1f4
main.printChain(0x1, {0x529798, 0xc0000a0480})
	/home/daved/code/src/github.com/ActiveState/cli/cmd/errwraps/main.go:21 +0x1f4
main.printChain(0x0, {0x529798, 0xc0000a0500})
	/home/daved/code/src/github.com/ActiveState/cli/cmd/errwraps/main.go:21 +0x1f4
main.printAll({0x5045ab?, 0x406099?}, {0x50bd0d, 0x10d}, {0x0, 0x0}, {0x529798, 0xc0000a0500})
	/home/daved/code/src/github.com/ActiveState/cli/cmd/errwraps/main.go:43 +0x2bc
main.main()
	/home/daved/code/src/github.com/ActiveState/cli/cmd/errwraps/main.go:87 +0xb5
exit status 2
